[package]
name = "desc"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.2.7", features = ["derive"] }
reqwest = { version = "0.12.5", features = ["json", "blocking"] }
rfam = { path = "../rfam" }
serde.workspace = true
serde_json = "^1"
