[package]
name = "desc"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.2.7", features = ["derive"] }
desc-lib = { path = "../desc-lib" }
reqwest = { version = "0.12.5", features = ["json", "blocking"] }
serde_json = "1.0.124"
serde.workspace = true
