[workspace]
resolver = "2"
members = [
  "crates/desc",
  "crates/infernal",
  "crates/rfam",
  "crates/ols-api",
]

[workspace.dependencies]
derive_builder = "0.20.0"
serde = { version = "^1", features = ["derive"] }
strum = { version = "0.24.1", features = ["derive"] }
thiserror = "1.0.63"
