/*
 * OLS Service
 *
 * REST API for OLS
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1OboDefinitionCitation {
    #[serde(rename = "definition", skip_serializing_if = "Option::is_none")]
    pub definition: Option<String>,
    #[serde(rename = "oboXrefs", skip_serializing_if = "Option::is_none")]
    pub obo_xrefs: Option<Vec<models::V1OboXref>>,
}

impl V1OboDefinitionCitation {
    pub fn new() -> V1OboDefinitionCitation {
        V1OboDefinitionCitation {
            definition: None,
            obo_xrefs: None,
        }
    }
}
